"use client";
import type { NextPage } from "next";
import { useEffect, useRef, useState, type KeyboardEvent } from "react";
import HowItWorks from "./how-it-works";
import Step from "./step";

export type FrameComponent5Type = {
  className?: string;
};

type HowItWorksStep = {
  id: string;
  stepNumber: string;
  title: string;
  descriptions: readonly [string, string];
  imageSrc: string;
  thumbnailSrc: string;
  imageAlt: string;
  thumbnailAlt: string;
};

const HOW_IT_WORKS_STEPS: readonly HowItWorksStep[] = [
  {
    id: "upload",
    stepNumber: "01",
    title: "Upload or Connect",
    descriptions: [
      "Upload your content manually through the Wirero dashboard or connect your RSS feed for fully automated distribution.",
      "Publish instantly, automate recurring content flows, and manage distribution from a single centralized system.",
    ],
    imageSrc: "/Step 1.jpg",
    thumbnailSrc: "/Step 1.jpg",
    imageAlt: "Content ready to be uploaded through the Wirero dashboard",
    thumbnailAlt: "Preview of the upload or connect step",
  },
  {
    id: "reach",
    stepNumber: "02",
    title: "Select Your Reach",
    descriptions: [
      "Choose the industry-specific networks and number of domains that match your distribution goals.",
      "Control your reach from targeted niche publishing to large-scale deployment across the Wirero network.",
    ],
    imageSrc: "/Step 2.jpg",
    thumbnailSrc: "/Step 2.jpg",
    imageAlt: "Publisher selecting the reach for a distribution campaign",
    thumbnailAlt: "Preview of the select your reach step",
  },
  {
    id: "publish",
    stepNumber: "03",
    title: "Go Live Instantly",
    descriptions: [
      "Launch your content across the selected domains through one centralized publishing workflow.",
      "Pages are deployed quickly and can go live across the network in approximately one hour.",
    ],
    imageSrc: "/Step 3.jpg",
    thumbnailSrc: "/Step 3.jpg",
    imageAlt: "Fast publishing workflow sending content live",
    thumbnailAlt: "Preview of the go live instantly step",
  },
  {
    id: "reports",
    stepNumber: "04",
    title: "Track & Export",
    descriptions: [
      "Track completed placements and access the live URLs generated by each distribution campaign.",
      "Export clear campaign reports for your team, clients, or internal performance records.",
    ],
    imageSrc: "/Step 4.jpg",
    thumbnailSrc: "/Step 4.jpg",
    imageAlt: "Media reports available for tracking and export",
    thumbnailAlt: "Preview of the track and export step",
  },
] as const;

const PANEL_ID = "how-wirero-works-panel";
const MOBILE_PANEL_ORDER_CLASSES = [
  "mq450:order-0",
  "mq450:order-2",
  "mq450:order-4",
  "mq450:order-6",
] as const;
const MOBILE_TAB_ORDER_CLASSES = [
  "mq450:order-1",
  "mq450:order-3",
  "mq450:order-5",
  "mq450:order-7",
] as const;

const FrameComponent5: NextPage<FrameComponent5Type> = ({ className = "" }) => {
  const [activeStepIndex, setActiveStepIndex] = useState(0);
  const [displayedStepIndex, setDisplayedStepIndex] = useState(0);
  const [contentVisible, setContentVisible] = useState(true);
  const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const transitionTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const displayedStep = HOW_IT_WORKS_STEPS[displayedStepIndex];

  useEffect(() => {
    return () => {
      if (transitionTimerRef.current) {
        clearTimeout(transitionTimerRef.current);
      }
    };
  }, []);

  const selectStep = (nextIndex: number) => {
    if (nextIndex === activeStepIndex && contentVisible) {
      return;
    }

    if (transitionTimerRef.current) {
      clearTimeout(transitionTimerRef.current);
    }

    setActiveStepIndex(nextIndex);

    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      setDisplayedStepIndex(nextIndex);
      setContentVisible(true);
      return;
    }

    setContentVisible(false);
    transitionTimerRef.current = setTimeout(() => {
      setDisplayedStepIndex(nextIndex);
      setContentVisible(true);
    }, 150);
  };

  const handleTabKeyDown = (
    event: KeyboardEvent<HTMLButtonElement>,
    currentIndex: number,
  ) => {
    const lastIndex = HOW_IT_WORKS_STEPS.length - 1;
    let nextIndex: number | null = null;

    switch (event.key) {
      case "ArrowRight":
      case "ArrowDown":
        nextIndex = currentIndex === lastIndex ? 0 : currentIndex + 1;
        break;
      case "ArrowLeft":
      case "ArrowUp":
        nextIndex = currentIndex === 0 ? lastIndex : currentIndex - 1;
        break;
      case "Home":
        nextIndex = 0;
        break;
      case "End":
        nextIndex = lastIndex;
        break;
      default:
        return;
    }

    event.preventDefault();
    selectStep(nextIndex);
    tabRefs.current[nextIndex]?.focus();
  };

  return (
    <div
      className={`w-full flex flex-col items-center mq450:gap-[1.25rem] ${className}`}
    >
      <Step
        className={MOBILE_PANEL_ORDER_CLASSES[activeStepIndex]}
        stepNumber={displayedStep.stepNumber}
        title={displayedStep.title}
        descriptions={displayedStep.descriptions}
        imageSrc={displayedStep.imageSrc}
        imageAlt={displayedStep.imageAlt}
        panelId={PANEL_ID}
        labelledBy={`how-wirero-works-tab-${displayedStep.id}`}
        contentVisible={contentVisible}
      />
      <section className="w-full min-w-0 flex items-start justify-center py-0 px-[clamp(0rem,4vw,4.25rem)] box-border max-w-full mt-[-7.125rem] relative z-[2] text-center text-[1rem] text-[#0bc111] font-proxima mq1125:mt-0 mq1125:px-0 mq450:contents">
        <div
          role="tablist"
          aria-label="How Wirero Works steps"
          className="w-full max-w-full min-w-0 grid grid-cols-4 items-end gap-[1.25rem] mq1125:grid-cols-2 mq450:contents"
        >
          {HOW_IT_WORKS_STEPS.map((item, index) => (
            <HowItWorks
              key={item.id}
              className={MOBILE_TAB_ORDER_CLASSES[index]}
              buttonRef={(element) => {
                tabRefs.current[index] = element;
              }}
              tabId={`how-wirero-works-tab-${item.id}`}
              panelId={PANEL_ID}
              thumbnailSrc={item.thumbnailSrc}
              thumbnailAlt={item.thumbnailAlt}
              stepNumber={item.stepNumber}
              title={item.title}
              isActive={index === activeStepIndex}
              onClick={() => selectStep(index)}
              onKeyDown={(event) => handleTabKeyDown(event, index)}
            />
          ))}
        </div>
      </section>
    </div>
  );
};

export default FrameComponent5;
